### ISSUE TITLE
Get-PfaVolumeSpaceMetrics does not show values for system and shared_space properties

### ISSUE THREAD

**Issue by Sergong** [PureStorage-Connect/PowerShellSDK#1]
Using version 1.13 on FA//M20R2 the Get-PfaVolumeSpaceMetrics cmdlet does not show values for the system and shared_space properties (see output below).

The array is running Purity version 5.1.2

PS E:\Scripts> Get-PfaVolumeSpaceMetrics -Array $FlashArray -VolumeName DXS_PS1_MIG_DS01

total             : 907866958158
name              : DXS_PS1_MIG_DS01
system            : 
snapshots         : 0
volumes           : 907866958158
data_reduction    : 3.1808603387010765
size              : 10995116277760
shared_space      : 
thin_provisioning : 0.7150385623332113
total_reduction   : 11.162423816869293

**Comment by mikenelson-io** [comment]
Stale.
