### ISSUE TITLE
Powershell Core?

### ISSUE THREAD

**Issue by eoq** [PureStorage-Connect/PowerShellSDK#2]
As far as I can tell this SDK requires Powershell and does not work with PowerShell Core (https://github.com/PowerShell/PowerShell) so therefore only works on Windows.
If that is true, do you have a Powershell Core support on the roadmap? Rough timeline?
Thanks
Ed

**Comment by codyhosterman** [comment]
This is on the roadmap, though exactly when this update will occur is not yet fully committed yet.

**Comment by barkz** [comment]
Right now we are focused on support for PowerShell SDK for REST 2.0. Core support is on the roadmap as Cody mentioned but it has not been prioritized yet, so cannot give a timeframe.

**Comment by eoq** [comment]
Thanks. I will pull and test as soon as I see something drop.
